[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
evm_version = "cancun"
via_ir = true
optimizer_runs = 1000000
fs_permissions = [{ access = "read", path = "./" }]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY_ETHEREUM}", url = "${ETHERSCAN_URL_ETHEREUM}" }
optimism = { key = "${ETHERSCAN_API_KEY_OPTIMISM}", url = "${ETHERSCAN_URL_OPTIMISM}" }
polygon = { key = "${ETHERSCAN_API_KEY_POLYGON}", url = "${ETHERSCAN_URL_POLYGON}" }
arbitrum = { key = "${ETHERSCAN_API_KEY_ARBITRUM}", url = "${ETHERSCAN_URL_ARBITRUM}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
